# Generated by Django 2.1.3 on 2018-11-16 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=3)),
                ('image_url', models.CharField(max_length=500)),
                ('tour_points', models.IntegerField()),
                ('elo_points', models.IntegerField()),
            ],
            options={
                'ordering': ('tour_points',),
            },
        ),
    ]
