# Generated by Django 2.1.4 on 2019-01-14 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('image_url', models.CharField(max_length=500)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('ranking_tour', models.IntegerField(blank=True, null=True)),
                ('ranking_tour_highest', models.IntegerField(blank=True, null=True)),
                ('ranking_tour_change', models.IntegerField(blank=True, null=True)),
                ('ranking_elo', models.IntegerField(blank=True, null=True)),
                ('ranking_elo_highest', models.IntegerField(blank=True, null=True)),
                ('ranking_elo_change', models.IntegerField(blank=True, null=True)),
                ('current_tournament_name', models.CharField(blank=True, max_length=100, null=True)),
                ('current_tournament_round', models.CharField(blank=True, max_length=100, null=True)),
                ('in_tournament', models.BooleanField(default=False)),
                ('video', models.CharField(blank=True, max_length=500, null=True)),
                ('points_tour_live', models.IntegerField(blank=True, null=True)),
                ('points_tour_next', models.IntegerField(blank=True, null=True)),
                ('points_tour_change', models.IntegerField(blank=True, null=True)),
                ('elo_tour_live', models.IntegerField(blank=True, null=True)),
                ('elo_tour_next', models.IntegerField(blank=True, null=True)),
                ('elo_tour_change', models.IntegerField(blank=True, null=True)),
                ('next_prob', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ('-points_tour_live',),
            },
        ),
    ]
